<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Job;
use Carbon\Carbon;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Assistant Professor - Computer Science',
                'item_number' => 'ITEM-001',
                'campus' => 'Main Campus',
                'vacancies' => 2,
                'description' => 'Teach computer science courses, conduct research, and mentor students in the Computer Science program. Must have a Master\'s degree in Computer Science or related field.',
                'department' => 'College of Engineering',
                'position_type' => 'Full-time',
                'salary' => 45000.00,
                'application_deadline' => Carbon::now()->addDays(30),
                'education_requirements' => 'Master\'s degree in Computer Science or related field',
                'experience_requirements' => 'At least 2 years of teaching experience preferred',
                'training_requirements' => 'Teaching methodology training',
                'eligibility_requirements' => 'Licensed Professional Teacher or equivalent',
                'is_published' => true,
            ],
            [
                'title' => 'Administrative Assistant - Registrar Office',
                'item_number' => 'ITEM-002',
                'campus' => 'Main Campus',
                'vacancies' => 1,
                'description' => 'Assist in student records management, enrollment processes, and academic documentation. Must have excellent organizational skills and attention to detail.',
                'department' => 'Registrar Office',
                'position_type' => 'Full-time',
                'salary' => 25000.00,
                'application_deadline' => Carbon::now()->addDays(20),
                'education_requirements' => 'Bachelor\'s degree in any field',
                'experience_requirements' => 'At least 1 year of administrative experience',
                'training_requirements' => 'Office management training',
                'eligibility_requirements' => 'Civil Service Eligibility preferred',
                'is_published' => true,
            ],
            [
                'title' => 'Librarian - Learning Resource Center',
                'item_number' => 'ITEM-003',
                'campus' => 'Main Campus',
                'vacancies' => 1,
                'description' => 'Manage library resources, assist students and faculty with research, and maintain digital collections. Master\'s in Library Science preferred.',
                'department' => 'Learning Resource Center',
                'position_type' => 'Full-time',
                'salary' => 30000.00,
                'application_deadline' => Carbon::now()->addDays(15),
                'education_requirements' => 'Bachelor\'s degree in Library Science or related field, Master\'s preferred',
                'experience_requirements' => 'Library management experience preferred',
                'training_requirements' => 'Digital library systems training',
                'eligibility_requirements' => 'Licensed Librarian preferred',
                'is_published' => true,
            ],
            [
                'title' => 'IT Support Specialist',
                'item_number' => 'ITEM-004',
                'campus' => 'Main Campus',
                'vacancies' => 1,
                'description' => 'Provide technical support for computer systems, networks, and educational technology. Must have experience with Windows, Linux, and network administration.',
                'department' => 'Information Technology Services',
                'position_type' => 'Full-time',
                'salary' => 35000.00,
                'application_deadline' => Carbon::now()->addDays(25),
                'education_requirements' => 'Bachelor\'s degree in Information Technology, Computer Science, or related field',
                'experience_requirements' => 'At least 2 years of IT support experience',
                'training_requirements' => 'Network administration and security training',
                'eligibility_requirements' => 'IT certifications preferred (CCNA, CompTIA, etc.)',
                'is_published' => true,
            ],
            [
                'title' => 'Student Affairs Coordinator',
                'item_number' => 'ITEM-005',
                'campus' => 'Main Campus',
                'vacancies' => 1,
                'description' => 'Organize student activities, manage student organizations, and provide student support services. Must have experience in student development and event planning.',
                'department' => 'Student Affairs',
                'position_type' => 'Part-time',
                'salary' => 20000.00,
                'application_deadline' => Carbon::now()->addDays(10),
                'education_requirements' => 'Bachelor\'s degree in Education, Psychology, or related field',
                'experience_requirements' => 'Experience in student development and event planning',
                'training_requirements' => 'Student leadership and counseling training',
                'eligibility_requirements' => 'Civil Service Eligibility preferred',
                'is_published' => true,
            ],
            [
                'title' => 'Research Assistant - Engineering',
                'item_number' => 'ITEM-006',
                'campus' => 'Main Campus',
                'vacancies' => 2,
                'description' => 'Assist faculty in research projects, data collection, and laboratory management. Must be enrolled in or graduated from an engineering program.',
                'department' => 'College of Engineering',
                'position_type' => 'Contract',
                'salary' => 18000.00,
                'application_deadline' => Carbon::now()->addDays(12),
                'education_requirements' => 'Currently enrolled in or graduated from an Engineering program',
                'experience_requirements' => 'Research experience preferred',
                'training_requirements' => 'Research methodology training',
                'eligibility_requirements' => 'None required',
                'is_published' => false,
            ],
            [
                'title' => 'Campus Security Guard',
                'item_number' => 'ITEM-007',
                'campus' => 'Main Campus',
                'vacancies' => 3,
                'description' => 'Ensure campus safety and security, monitor facilities, and assist with emergency response. Must have security training and good physical condition.',
                'department' => 'Security Services',
                'position_type' => 'Full-time',
                'salary' => 22000.00,
                'application_deadline' => Carbon::now()->addDays(18),
                'education_requirements' => 'High school diploma or equivalent',
                'experience_requirements' => 'Security guard experience preferred',
                'training_requirements' => 'Security guard training and first aid certification',
                'eligibility_requirements' => 'Security guard license required',
                'is_published' => true,
            ],
            [
                'title' => 'Maintenance Worker',
                'item_number' => 'ITEM-008',
                'campus' => 'Main Campus',
                'vacancies' => 2,
                'description' => 'Perform general maintenance and repairs on campus facilities, equipment, and infrastructure. Must have basic technical skills and tools knowledge.',
                'department' => 'Facilities Management',
                'position_type' => 'Full-time',
                'salary' => 20000.00,
                'application_deadline' => Carbon::now()->addDays(14),
                'education_requirements' => 'High school diploma or vocational training',
                'experience_requirements' => 'Maintenance or repair experience preferred',
                'training_requirements' => 'Basic maintenance and safety training',
                'eligibility_requirements' => 'None required',
                'is_published' => true,
            ],
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        }
    }
}